builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: 386
archive:
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brew:
  github:
    owner: mpppk
    name: homebrew-mpppk
  homepage: "https://github.com/mpppk/hlb"
  description: "CLI that provides unified & interactive interface to multiple git repository hosting services"
  dependencies:
    - peco
  test: |
    system "#{bin}/hlb --help"